### ISSUE TITLE
Gather information on the NESE cluster

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/storage-benchmarks#1]
> Node count, disks per node, network per node, latency metrics from both cluster and disk
> Some notion of performance utilization, ie is it heavily loaded or typically idle

**Comment by joachimweyl** [comment]
Please open an issue through the NESE ticketing system

**Comment by msdisme** [comment]
Some details here: https://nese.mghpcc.org/support/ (probably not what you need) and support request email: help@nese.mghpcc.org

**Comment by knikolla** [comment]
Sent an email to the support request email. Will update this comment with ticket information once I receive it. 

EDIT: Ticket link https://mghpcc.supportsystem.com/tickets.php?id=12283

**Comment by joachimweyl** [comment]
@syockel or @jtriley do we have a way to escalate NESE tickets?

**Comment by syockel** [comment]
Yes, to me.  

Are there any tickets specifically that need my eyes on them currently?

**Comment by joachimweyl** [comment]
This ticket please https://mghpcc.supportsystem.com/tickets.php?id=12283

**Comment by syockel** [comment]
I don't have access to that ticket.

**Comment by syockel** [comment]
Oh I found it, it is ticket number  Ticket #004090.  The link you provided doesn't work when you are an agent and not just a end-user.  This link works for me: https://mghpcc.supportsystem.com/scp/tickets.php?id=12283

**Comment by joachimweyl** [comment]
@knikolla is this resolved?

**Comment by knikolla** [comment]
Yes, I have received a response and have a channel of communication open in case of future queries.
